spring:
  cloud:
    nacos:
      username: nacos
      password: zjh@123
      discovery:
        # 说明：${}取值的优先级一般为：
        #   1、命令行参数。如java -jar app.jar --NACOS_HOST=127.0.0.1
        #   2、环境变量。如export NACOS_HOST=127.0.0.1
        #                java -jar app.jar
        #   3、配置文件。如application.yml
        #   4、远程配置中心。nacos等
        server-addr: ${NACOS_HOST:113.44.162.189}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:${spring.application.name}.yml
      - nacos:mybatis.yml
